network:
    version: 2
    renderer: networkd
    ethernets:
      eth0:
        dhcp4: yes
      eth1:
        dhcp4: no
        addresses: [192.168.0.250/24]
        gateway4: 192.168.0.1
        nameservers:
          addresses: [192.168.0.1]
          search: [simulation]
